export const STORE_KEY_EDIT_POD = 'pods/edit-pod';

export const DELETE_STATUSES = {
	NONE: '',
	DELETING: 'DELETING',
	DELETE_SUCCESS: 'DELETE_SUCCESS',
	DELETE_ERROR: 'DELETE_ERROR',
};

export const SAVE_STATUSES = {
	NONE: '',
	SAVING: 'SAVING',
	SAVE_SUCCESS: 'SAVE_SUCCESS',
	SAVE_ERROR: 'SAVE_ERROR',
	DELETE_ERROR: 'DELETE_ERROR',
};

export const DRAG_ITEM_TYPES = {
	GROUP: 'GROUP',
	FIELD: 'FIELD',
};

export const UI_ACTIONS = {
	SET_ACTIVE_TAB: 'UI/SET_ACTIVE_TAB',

	SET_SAVE_STATUS: 'UI/SET_SAVE_STATUS',
	SET_DELETE_STATUS: 'UI/SET_DELETE_STATUS',

	SET_GROUP_SAVE_STATUS: 'UI/SET_GROUP_SAVE_STATUS',
	SET_GROUP_DELETE_STATUS: 'UI/SET_GROUP_DELETE_STATUS',

	SET_FIELD_SAVE_STATUS: 'UI/SET_FIELD_SAVE_STATUS',
	SET_FIELD_DELETE_STATUS: 'UI/SET_FIELD_DELETE_STATUS',
};

export const CURRENT_POD_ACTIONS = {
	SET_POD_NAME: 'CURRENT_POD/SET_POD_NAME',
	SET_OPTION_VALUE: 'CURRENT_POD/SET_OPTION_ITEM_VALUE',
	SET_OPTIONS_VALUES: 'CURRENT_POD/SET_OPTIONS_VALUES',

	SET_GROUP_LIST: 'CURRENT_POD/SET_GROUP_LIST',
	MOVE_GROUP: 'CURRENT_POD/MOVE_GROUP',
	ADD_GROUP: 'CURRENT_POD/ADD_GROUP',
	REMOVE_GROUP: 'CURRENT_POD/REMOVE_GROUP',
	SET_GROUP_FIELDS: 'CURRENT_POD/SET_GROUP_FIELDS',
	ADD_GROUP_FIELD: 'CURRENT_POD/ADD_GROUP_FIELD',
	SET_GROUP_DATA: 'CURRENT_POD/SET_GROUP_DATA',

	API_REQUEST: 'CURRENT_POD/API_REQUEST',
};

export const INITIAL_UI_STATE = {
	activeTab: 'manage-fields',
	saveStatus: SAVE_STATUSES.NONE,
	deleteStatus: DELETE_STATUSES.NONE,
	saveMessage: null,
	deleteMessage: null,
	groupSaveStatuses: {},
	groupDeleteStatuses: {},
	fieldSaveStatuses: {},
	fieldDeleteStatuses: {},
};
