export const TEXT_FIELD = {
	admin_only: '0',
	description: '',
	group: '122',
	hidden: '0',
	id: 119,
	label: 'Text Field',
	name: 'text_field',
	object_type: 'field',
	parent: 117,
	read_only: '0',
	required: '0',
	rest_pick_depth: '2',
	rest_pick_response: 'array',
	rest_read: '0',
	rest_write: '0',
	restrict_capability: '0',
	restrict_role: '0',
	roles_allowed: [ 'administrator' ],
	storage_type: 'post_type',
	text_allow_html: '0',
	text_allow_shortcode: '0',
	text_allowed_html_tags: 'strong em a ul ol li b i',
	text_max_length: '255',
	type: 'text',
	weight: 0,
};

export const GROUP = {
	description: '',
	id: 122,
	label: 'More Fields',
	name: 'more-fields',
	object_type: 'group',
	parent: 117,
	storage_type: 'post_type',
	weight: 0,
	fields: [
		TEXT_FIELD,
	],
};

export const POD = {
	built_in_taxonomies_category: '0',
	built_in_taxonomies_link_category: '0',
	built_in_taxonomies_post_tag: '0',
	can_export: '1',
	capability_type: 'post',
	capability_type_custom: 'test',
	capability_type_extra: '1',
	default_status: 'draft',
	description: '',
	exclude_from_search: '0',
	has_archive: '0',
	hierarchical: '0',
	id: 117,
	label: 'tests',
	label_add_new: 'Add New Something',
	label_singular: 'test',
	menu_position: '0',
	name: 'test',
	object_type: 'pod',
	pfat_append_archive: 'append',
	pfat_append_single: 'append',
	pfat_enable: '0',
	pfat_filter_archive: 'the_content',
	pfat_filter_single: 'the_content',
	pfat_run_outside_loop: '0',
	public: '1',
	publicly_queryable: '1',
	query_var: '1',
	read_all: '0',
	rest_enable: '0',
	rewrite: '1',
	rewrite_feeds: '0',
	rewrite_pages: '1',
	rewrite_with_front: '1',
	show_in_admin_bar: '1',
	show_in_menu: '1',
	show_in_nav_menus: '1',
	show_ui: '1',
	storage: 'meta',
	storage_type: 'post_type',
	supports_author: '0',
	supports_comments: '0',
	supports_custom_fields: '0',
	supports_editor: '1',
	supports_excerpt: '0',
	supports_page_attributes: '0',
	supports_post_formats: '0',
	supports_revisions: '0',
	supports_thumbnail: '0',
	supports_title: '1',
	supports_trackbacks: '0',
	type: 'post_type',
	write_all: '0',
	_locale: 'user',
	groups: [
		GROUP,
	],
};

export const GLOBAL_POD = {
	description: 'Pod configuration',
	id: '',
	internal: true,
	label: 'Pod',
	name: '_pods_pod',
	object_type: 'pod',
	storage_type: 'collection',
	groups: [
		{
			description: '',
			id: '',
			label: 'Labels',
			name: 'labels',
			object_type: 'group',
			parent: '_pods_pod',
			storage_type: 'collection',
			fields: [
				{
					default: 'test',
					description: '',
					group: 'group/_pods_pod/labels',
					help: 'help',
					id: '',
					label: 'Label',
					name: 'label',
					object_type: 'field',
					parent: '_pods_pod',
					storage_type: 'collection',
					text_max_length: 30,
					type: 'text',
				},
			],
		},
		{
			description: '',
			id: '',
			label: 'REST API',
			name: 'rest-api',
			object_type: 'group',
			parent: '_pods_pod',
			storage_type: 'collection',
			fields: [
				{
					default: '',
					dependency: true,
					description: '',
					group: 'group/_pods_pod/rest-api',
					help: 'Add REST API support for this Pod.',
					id: '',
					label: 'Enable',
					name: 'rest_enable',
					object_type: 'field',
					parent: '_pods_pod',
					storage_type: 'collection',
					type: 'boolean',
				},
				{
					default: '',
					'depends-on': { rest_enable: true },
					description: '',
					group: 'group/_pods_pod/rest-api',
					help: 'This will form the url for the route. Default / empty value here will use the pod name.',
					id: '',
					label: 'REST Base (if any)',
					name: 'rest_base',
					object_type: 'field',
					parent: '_pods_pod',
					storage_type: 'collection',
					type: 'text',
				},
			],
		},
	],
};

export const GLOBAL_GROUP = {
	description: 'Pod Group configuration',
	groups: [],
	id: '',
	internal: true,
	label: 'Pod Group',
	name: '_pods_group',
	object_type: 'pod',
	storage_type: 'collection',
};

export const TEST_CONFIG_DATA = {
	currentPod: POD,
	global: {
		pod: GLOBAL_POD,
	},
};
