global.document = require( 'jsdom' ).jsdom( '<html></html>' );
global.window = document.defaultView;
global.jQuery = require( 'jquery' );
global._ = require( 'underscore' );
global.Backbone = require( 'backbone' );
global.Marionette = require( 'backbone.marionette' );
global.assert = require( 'assert' );
global.wp = { media: { view: { Frame: { extend : function(){} } } } }; // Stub
global.PodsI18n = { __: function( str ){ return str; } }; // Stub for now