<?php //[STAMP] 72fa8e79eafcde3c7eb3dc8335b6f9fb
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait IntegrationTesterActions {

	/**
	 * @return \Codeception\Scenario
	 */
	abstract protected function getScenario();

	/**
	 * [!] Method is generated. Documentation taken from corresponding module.
	 *
	 * Calls a list of user-defined actions needed in tests.
	 * @see \Codeception\Module\WPLoader::bootstrapActions()
	 */
	public function bootstrapActions() {
		return $this->getScenario()->runStep( new \Codeception\Step\Action( 'bootstrapActions', func_get_args() ) );
	}

	/**
	 * [!] Method is generated. Documentation taken from corresponding module.
	 *
	 *
	 * @see \Codeception\Module\WPLoader::activatePlugins()
	 */
	public function activatePlugins() {
		return $this->getScenario()->runStep( new \Codeception\Step\Action( 'activatePlugins', func_get_args() ) );
	}

	/**
	 * [!] Method is generated. Documentation taken from corresponding module.
	 *
	 * Loads the plugins required by the test.
	 * @see \Codeception\Module\WPLoader::loadPlugins()
	 */
	public function loadPlugins() {
		return $this->getScenario()->runStep( new \Codeception\Step\Action( 'loadPlugins', func_get_args() ) );
	}

	/**
	 * [!] Method is generated. Documentation taken from corresponding module.
	 *
	 * Accessor method to get the object storing the factories for things.
	 *
	 * Example usage:
	 *
	 *        $postId = $I->factory()->post->create();
	 *
	 * @return \tad\WPBrowser\Module\WPLoader\FactoryStore
	 * @see \Codeception\Module\WPLoader::factory()
	 */
	public function factory() {
		return $this->getScenario()->runStep( new \Codeception\Step\Action( 'factory', func_get_args() ) );
	}
}
