name: Generate Playground
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  preview:
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: WordPress/action-wp-playground-pr-preview@v3
        with:
          plugin-path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
